add_lunch_combo pa_galaxys2-userdebug
add_lunch_combo pa_i9300-userdebug
add_lunch_combo pa_maguro-userdebug
add_lunch_combo pa_toro-userdebug
add_lunch_combo pa_toroplus-userdebug
add_lunch_combo pa_shadow-userdebug
add_lunch_combo pa_droid2-userdebug
add_lunch_combo pa_droid2we-userdebug
